name: axum-service-starter

services:
    openobserve:
        networks:
            - backend
        image: public.ecr.aws/zinclabs/openobserve:latest
        restart: unless-stopped
        environment:
            - ZO_ROOT_USER_EMAIL=
            - ZO_ROOT_USER_PASSWORD=
            - ZO_TELEMETRY=false
        ports:
            - "5080:5080"
            - "5081:5081"
        volumes:
            - data:/data

    axum_service_starter:
        networks:
            - backend
        build:
            context: ../../
            dockerfile: Dockerfile
        image: axum-service-starter
        ports:
            - "8080:8080"
        environment:
            - OTEL_SERVICE_NAME=axum-service-starter
            - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://openobserve:5081
            - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://openobserve:5081
            - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://openobserve:5081
            - OTEL_METRIC_EXPORT_INTERVAL=10000
            - RUST_LOG=info,axum_service_starter=debug,tower_http=debug
            - SERVER_ENVIRONMENT=development
            - APP_NAME=axum-service-starter
            - OTEL_SDK_DISABLED=false
            - OTEL_PROVIDER=openobserve
            - OTEL_PROVIDER_ORGANIZATION=default
            - OTEL_PROVIDER_STREAM_NAME=axum-service-starter
            - OTEL_PROVIDER_AUTH_TOKEN=
        depends_on:
            - openobserve

networks:
    backend:

volumes:
    data:
